Controllers/LoanController.cs
using Loan.Data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Loan.Data.Models;
using System.Web.Routing;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Loan.Data;
using LoanEvaluator;
using Microsoft.AspNet.Identity;
using NLog;

namespace LoanComparerApp.Controllers
{
  public class LoanController : Controller
  {
    ILoan db;
    IMapLoan maps;
    private readonly ILoanProvides _pd;
    private readonly ITracker _tracker;
    private readonly ISubscribed _subscribed;
    Logger _logger = LogManager.GetCurrentClassLogger();
    public LoanController(ILoan db, IMapLoan map, ILoanProvides pd, ITracker tracker,ISubscribed subscribed)
    {
      this.db = db;
      this.maps = map;
      _pd = pd;
      _tracker = tracker;
      _subscribed = subscribed;
    }

    [HttpGet]
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult AllLoan()
    {
      var model = db.GetAll();
      if (model == null)
      {
        return RedirectToAction("NotFound");
      }

      return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Index(Loans loan)
    {
      try
      {
        db.Clear();
        db.Add(loan);
      }
      catch (Exception e)
      {
       _logger.Error(e.Message);
        
      }
    
      return RedirectToAction("CheckSite");
    }

    public ActionResult NotFound()
    {
      return View();
    }

    public ActionResult CheckSite()
    {
      var model = maps.GetAll(db.GetLoans().amountToBeBorrrowed);
      try
      {

     
      if (model == null)
      {
        return RedirectToAction("NotFound");
      }

      if (model.ToList().Count == 0)
      {
        return RedirectToAction("NotFound");
      }
      }
      catch (Exception e)
      {
       _logger.Error(e.Message );
      }
      return View(model);
    }

    [Authorize]
    public ActionResult SiteDetails(int Id)
    {
      if (!ModelState.IsValid)
      {
        return RedirectToAction("NotFound");
      }
      
      var model = maps.Get(Id);
      ViewBag.id = Id;
      db.CalculateInterest(model.Rate);
      var models = db.Get();

      if (models == null)
      {
        return RedirectToAction("NotFound");
      }

      models.WebsiteName = model.Loansite;
      models.Rate = model.Rate;
      models.CalculatedLoan = db.CalculateInterest(model.Rate);

      return View(models);
    }

    public ActionResult Redirect(int Id)
    {
      var model = maps.Get(Id);
      var userId = User.Identity.GetUserId();
      if (model == null)
      {
        return RedirectToAction("NotFound");
      }

      var website = model.websitelink;
      if (_subscribed.GetSubscribedByUserId(userId).Count > 0)
      {
        _tracker.AddToTracker(model.Loansite, userId);
        var checkIfUserIsAvailable = _tracker.GetvaluebyproviderNameAndUserid(model.Loansite, userId);
        if (checkIfUserIsAvailable)
        {
          var providertoupdate1 = _pd.GEtLoanProvidersbyName(model.Loansite);
          providertoupdate1.CountVisit += 1;
          if (_pd.Commit())
          {
            return Redirect(website);
          }

        }

        var providertoupdate = _pd.GEtLoanProvidersbyName(model.Loansite);
        providertoupdate.UniqueCountVisit += 1;
        providertoupdate.CountVisit += 1;
        _pd.UpdateLoanProvides(providertoupdate);
        _pd.Commit();
        return Redirect(website);
      }

      var returnUrl = Request.Url.ToString();
      BusinessLogic.UrlList.Add(returnUrl);
      var routeValues = new RouteValueDictionary
      {
        {"id", Id},
        {"returnUrl", returnUrl}
      };

      return RedirectToAction("Subscribe", "Subscribed", routeValues
    );
  }

    [HttpGet]
    public ActionResult CreateLoan()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CreateLoan(MapLoans loan)
    {
      if (loan == null)
      {
        return RedirectToAction("NotFound");
      }

      TempData["message"] = "you have successfully  created another loan ";
      maps.Add(loan);
      return RedirectToAction("AllMapLoan");
    }

    public ActionResult ALlMapLoan()
    {
      var model = maps.GetAlls();
      return View(model);
    }

    public ActionResult Loanprovider()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Loanprovider(LoanProviders providers)
    {
      _pd.AddLoanProvides(providers);
      _pd.Commit();
      return View();
    }
  }
}

Views/Shared/_DisplayCount.cshtml
@model Loan.Data.Models.DisplayCount

<div>
    <h4>DisplayCount</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProvideName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProvideName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UniqueCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniqueCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VisitCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisitCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div class="container fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
        <a class="navbar-brand" href="#">
            @Html.ActionLink("LoanComparer", "Index", "Loan", new { area = "" }, new { @class = "navbar-brand" })
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active navbar-text ml-5">
                    <a class="nav-link text-white" href="#">@Html.ActionLink("Home", "Index", "Loan") <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item navbar-text ml-5">
                    <a class="nav-link" href="#">@Html.ActionLink("view loans", "AllLoan", "Loan")</a>
                </li>
                <li class="nav-item navbar-text ml-4">
                    <a class="nav-link" href="#">@Html.ActionLink("Create", "CreateLoan", "Loan")</a>
                </li>
                <li class="nav-item navbar-text ml-5">
                    <a class="nav-link" href="#">@Html.ActionLink("maploan", "AllMaploan", "Loan")</a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")

        </div>

    </nav>
</div>
<div>
    @RenderBody()
    <footer class="container mt-5">
        <p>&copy; @DateTime.Now.Year - loan Comparer</p>
    </footer>
</div>
@Scripts.Render("~/bundles/jquery")




@RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_subscribepackage.cshtml
 

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="/Content/Subscribe.css" />
<!------ Include the above in your HEAD tag ---------->
HTML CSSResult
EDIT ON
<!-- Button trigger modal -->

           
                <div class="pricing-wrapper clearfix">
                    <!-- Titulo -->
                    <h1 class="pricing-table-title text-center text-danger " style="text-transform: uppercase"> Subscription </h1>
@using (Html.BeginForm())
{
    <div class="pricing-table">
        <h3 class="pricing-title">Basic</h3>
        <div class="price">&#8358;<sup>/ mes</sup></div>
        <ul class="table-list">
            <li>Access more Loan <span> providers</span></li>
            <li>receive update <span>Latest Loan providers</span></li>
            <li>Unlimited Access <span class="unlimited">Huge Loan provider with little interest</span></li>
            <li>one <span class="unlimited">Months</span></li>
            <input type="hidden" name=" sub" value="5000"/>
        </ul>
        <div class="table-buy">
            <p>$60<sup>/ mes</sup></p>
            <p>$60<sup>/ mes</sup></p>
            <button type="submit" class="pricing-action">Subscribe</button>
        </div>
    </div>
}
                    <div class="pricing-table recommended">
                        <h3 class="pricing-title">Premium</h3>
                        <div class="price">&#8358;10,000<sup>/ mes</sup></div>
                        <ul class="table-list">
                            <li>Access more Loan <span> providers</span></li>
                            <li>receive update <span>Latest Loan providers</span></li>
                            <li>Unlimited Access <span class="unlimited">Huge Loan provider with little interest</span></li>
                            <li>three <span class="unlimited">Months</span></li>
                        </ul>
                        <div class="table-buy">
                            <p>$100<sup>/ mes</sup></p>
                            <a href="#" class="pricing-action">SubScribe</a>
                        </div>
                    </div>

                    <div class="pricing-table">
                        <h3 class="pricing-title">Ultimate</h3>
                        <div class="price">&#8358;15,000<sup>/ mes</sup></div>
                        <ul class="table-list">
                            <li>Access more Loan <span> providers</span></li>
                            <li>receive update <span>Latest Loan providers</span></li>
                            <li>Unlimited Access <span class="unlimited">Huge Loan provider with little interest</span></li>
                            <li>six <span class="unlimited">Months</span></li>
                        </ul>
                        <!-- Contratar / Comprar -->
                        <div class="table-buy">
                            <p>$200<sup>/ mes</sup></p>
                            <a href="#" class="pricing-action">Subscribe</a>
                        </div>
                    </div>
                </div>